### ISSUE TITLE
shutdown behavior of SqsAckSinkStageGraphLogic

### ISSUE THREAD

**Issue by philotimos** [s12v/akka-stream-sqs#6]
When a message is processed by SQS it appears the stream is shutdown after the message is deleted.  In https://github.com/s12v/akka-stream-sqs/blob/master/src/main/scala/me/snov/akka/sqs/shape/SqsAckSinkGraphStageLogic.scala#111, methods handleDelete and handleSend call tryShutdown(), but I was not expecting the graph to be shutdown at this point since the README mentions "This stream listens for new messages and never stops.", but it's not clear if this is for just the listening of initial messages from SQS or after a DeleteMessageRequest as well.  What is the intended behavior?

**Comment by s12v** [comment]
@aeffrig, it calls `tryShutdown()`, but this method does nothing unless upstream already asked for shutdown (see `onUpstreamFinish()`). This is done to delay shutdown until all the inflight messages have been processed. I hope it works as intended :)

**Comment by philotimos** [comment]
Ok, that makes sense.  Thanks for the quick and clear explanation.
