### ISSUE TITLE
Cross publish for 2.12.1

### ISSUE THREAD

**Issue by calvinlfer** [s12v/akka-stream-sqs#9]
Hello there, 

I see that you have the process to cross-compile for 2.12.1 but I don't think you have published for 2.12.1 to Maven Central yet.

Thanks
Cal

**Comment by calvinlfer** [comment]
Hey @s12v, I'm really sorry to bug you but we really like this library and we're hoping you would cut a 2.12.1 release. It's the only library holding us back from doing an upgrade from 2.11.8 to 2.12.1

**Comment by s12v** [comment]
@calvinlfer, will do soon

**Comment by s12v** [comment]
@calvinlfer, done

**Comment by calvinlfer** [comment]
Thank you!
